
name: Analyze with CodeGuru Reviewer
on: [push]
permissions:
    id-token: write
    contents: read
    security-events: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      continue-on-error: true
      id: iam-role
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2
    
    - uses: actions/checkout@v3
      if: steps.iam-role.outcome == 'success'
      with:
        fetch-depth: 0

    - name: Use Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build 

    - name: CodeGuru Reviewer
      if: steps.iam-role.outcome == 'success'
      uses: aws-actions/codeguru-reviewer@v1.1
      continue-on-error: false
      with:          
        s3_bucket: codeguru-reviewer-github-profiler-demo-048169001733-uw2

    - name: Upload review result
      if: steps.iam-role.outcome == 'success'
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
